#!/bin/bash -eu

shopt -s expand_aliases

skip_ssl=${SKIP_SSL_VALIDATION:-false}
skip_ssl_flag=""

if ${skip_ssl}; then
    skip_ssl_flag="--skip-ssl-validation"
fi

alias om='om-linux ${skip_ssl_flag} --target "${OPSMAN_URL}" --username "${OPSMAN_USERNAME}" --password "${OPSMAN_PASSWORD}"'

om curl -p /api/v0/deployed/director/manifest > director_manifest.json

BOSH_CLIENT="ops_manager"
BOSH_CLIENT_SECRET=$(jq -r '.jobs[] | select(.name == "bosh") | .properties.uaa.clients.ops_manager.secret' director_manifest.json)
BOSH_ADDRESS=$(jq -r '.jobs[] | select(.name == "bosh") | .properties.director.address' director_manifest.json)

BOSH_CA_CERT_PATH="${PWD}/bosh.crt"
jq -r '.jobs[] | select(.name == "bosh") | .properties.director.config_server.ca_cert' director_manifest.json > "${BOSH_CA_CERT_PATH}"

export BOSH_CLIENT
export BOSH_CLIENT_SECRET
export BOSH_CA_CERT_PATH
export BOSH_ADDRESS
